version: 2.1

general:
  branches:
    only:
      - main
      - test-ci

jobs:
  build:
    docker:
      - image:  docker.l6.ee/builder/go:0.0.1@sha256:739ca532b13a4f3d5ff6bc824f02aa225e53b88d22a74368bab12ea15798a1dc
    resource_class: phntom/ornea
    steps:
      - checkout
      - run: make bootstrap
      - run:
          name: make test
          command: make test
          no_output_timeout: 30m
      - run: make build-cross
      - run: sudo pip install virtualenv && make acceptance

workflows:
  chartmuseum:
    jobs:
      - build
