version: 2.1

general:
  branches:
    only:
      - main
      - test-ci

jobs:
  build:
    docker:
      - image:  docker.l6.ee/builder/go:0.0.2@sha256:e9cca8997511614963dd0e681209efe62071f67e6a3021c4fb560a08b855de50
    resource_class: phntom/ornea
    steps:
      - checkout
      - run: make bootstrap
      - run:
          name: make test
          command: make test
          no_output_timeout: 30m
      - run: make build-cross
      - run: pip install virtualenv && make acceptance

workflows:
  chartmuseum:
    jobs:
      - build
